---
title: "An Introduction to Statistics & Programming"
format: 
  beamer:
    theme: berlin
    slide-number: true
    incremental: true  
    aspectratio: 169
    institute: Brian Fox
    navigation: frame
     

execute:
  echo: true
editor_options: 
  chunk_output_type: console
---

## Research I: Principles

<!-- don't forget to use the ipad to write on the slides as I go when needed -->

## Administration

Let's review the syllabus.

## A Taxonomy of Research

4 levels of research - basic disciplines, management, applied - lit review data-driven decision making, HBR

## Some Desirable Features of Research

1.  Falsifability:

. . . 

2.  Defensibility:

. . . 

3.  Replicability:

. . . 

4.  Applicability:

## Today's Readings

-   Falsifability: Popper, K. R. (2002)

-   Defensibility: Mantere, S., and Ketokivi, M. 2013

-   Replicability: Nosek, B. A. and Errington, T. M. 2020

-   Applicability: Rynes, S. L., and Bartunek, J. M. (2017)

## Falsifiability

> My proposal is based upon an asymmetry between verifiability and falsifiability; an asymmetry which results from the logical form of universal statements. For these are never derivable from singular statements, but can be contradicted by singular statements. - Popper (1962: 19)

## Defensibility

## Replicability

## Applicability

## Connections

-   Falsifiability provides a basis for abductive reasoning pure deductive reasoning is true a priori if the premises and statements are valid. We can transform our understanding of the system but generate additional truths - we may uncover them.

-   We worry about the defensibility of our arguments to be able to act upon the conclusions with confidence

-   But our arguments and conclusions are irrelevant if they aren't applcable to real-world problems; worries about inside baseball.

-   Finally, the structure of our empirical base presumes that the research was performed in good order and that the findings are replicable within their domain of applicability. This gets to the idea of trust but verify and the need to construct "stylized facts" (Kaldor, 1957, 1961; Helfat, 2007)
