---
title: "Pre-class Announcements"
format: 
    html: default

---

Hi everyone:

I look forward to seeing you all for the start of our Research Design course.

In preparation for our first class, I ask that you do three things:

1. Fill out this quick [Qualtrics survey](https://bentley.co1.qualtrics.com/jfe/form/SV_erJWo8SYdrte2p0) so that I can learn a  bit about you and your goals for the class. 

2. Review the [syllabus](https://briancfox.com/ResearchDesign/docs/syllabus.html)

3. Use the Dropbox link provided here on Brightspace to access and familiarize yourself the papers assigned for the first class.  Note that all links for the course are available in the "Course Materials" section of this site.

For your convenience, I note the readings for next class here (all are located in the folder in Dropbox beginning with "Class 1"):

  - Popper (2002) [Ch. 1 only!]
  
  - Mantere and Ketokivi (2013)
  
  - Nosek and Errington (2020)
  
  - Rynes and Bartunek (2017)

We will be discussing these readings, going through the syllabus, and otherwise preparing for the semester.  I will be continuing the update the site as we progress through the semester.  If you have any questions in the meantime, please feel free to reach out to me by email.

See you all soon!  I will be adding the Zoom login details to Brightspace shortly. 


