---
title: "Course Syllabus"
author: "Brian Fox"
format: 
  html: default
  pdf: 
      include-in-header: 
        text: |
          \usepackage{lscape}
          \newcommand{\blandscape}{\begin{landscape}}
          \newcommand{\elandscape}{\end{landscape}}
---

# PhD 1506 -- Research Design (Quant Research Methods I)

Dr. Brian Fox

**Office:** AAC G313

**Office Hours:** By appointment

**Email:** BFOX\@bentley.edu

**Meeting Time:** Tuesdays, 5 PM to 7 PM ET

**Location:** Zoom Meeting and Smith 307 when in person

**Course Format:** Hybrid Synchronous

Note: To download a pdf version of this syllabus, use the link provided to the right of this page.

## I. Course Description

This is an introductory seminar to research design for management science. Seminar participants will learn how to develop a research project and apply quantitative methods drawn from across the social sciences to achieve their aims.

## II. Course Objectives

This primary function of this course is to help advance your dissertation research. You will learn how to identify and articulate research questions, build models, develop hypotheses, and determine appropriate methods to address your research question. At a more granular level, my objectives are as follows:

-   Acquaint you with the research process

-   Facilitate your understanding of the management research context

-   Familiarize you with commonly employed quantitative methodologies and techniques

-   Demonstrate the need for theory-empiric fit in high-quality management research

-   Provide examples of specific research applications as toy models for your own work

-   Help you appreciate the subtle nature of research design

## III. Means and Methods

In support of these goals, we will employ the following format for the majority of our classes:

-   *Part I:* Conceptual grounding and agenda setting (10 minutes)

-   *Part II:* Core paper discussion (45 minutes):

    -   We will discuss the 2-3 papers that all students have been assigned to read in detail

    -   These papers typically will provide a mix of conceptual background and how-to guides

-   *Break* (5 minutes)

-   *Part III:* Activity period (40 minutes):

    -   (Weeks 2 -- 7) Compare / contrast: One group tasked with reviewing two additional papers to explain their points of intersection, divergence, and ties to core papers

    -   (Weeks 8 -- 14) Replication: One group tasked with using data from one of my current or published papers to replicate analyses and show the class the process

-   *Part IV:* Summative lecture on concepts (15 minutes):

    -   I will make a brief presentation to tie together and highlight key concepts

    -   Elements missed in the general discussion will be given greater focus

-   *Part V:* Open discussion (5 minutes)

-   *Part VI:* Workshop (4 hours, in-person meetings only):

    -   This is your opportunity to work with me and colleagues to advance your final project

## IV. Assignments and Grading

Everyone must read all required materials prior to class. Each student is expected to fully participate. All material due should be completed on Brightspace or sent to my email, depending on assignment requirements. Details on these assignments can be found in Appendix A.

| Task                                     | \% of Grade |
|------------------------------------------|-------------|
| Class participation -- paper discussions | 20          |
| Compare - contrast presentation          | 15          |
| Replication presentation                 | 15          |
| Concept checks (2)                       | 10          |
| Interim work on proposal                 | 15          |
| Final research proposal                  | 25          |
| **Total**                                | **100**     |

## V. Course Materials

### Reading List

Appendix B includes a list of required readings for the topics that we discuss. Supplemental reading materials are available, too -- I have omitted them from the reading list for your ease of reference, but I can send you a more complete version of the syllabus with the supplemental readings included if you are interested. I will also provide a number of good reference texts below -- again, none are required for the purpose of this class, but some will be invaluable as you continue your research methods journey, depending on your areas of interest and focus.

### Optional Text References

(Note: all provided for reference only, none of these texts are required).

#### *Research design texts*

-   Creswell, J.W. 2009. Research Design: Qualitative, Quantitative, and Mixed Methods Approaches, 3rd edition. Thousand Oaks, CA: Sage Publications).

-   Joseph Hair, Mary Wolfinbarger Celsi, Arthur Money, Phillip Samouel and Michael Page. 2011. Essentials of Business Research Methods, Hoboken, NJ: Wiley

-   Aguinis, H. 2024. Research Methodology: Best Practices for Rigorous, Credible, and Impactful Research. Sage Publications, Incorporated.

#### *Research methods texts*

-   Kennedy, P. 2008. A Guide to Econometrics (6th Edition). Malden, MA: Blackwell.

-   Pearl, J. 2001. Causality- Models, Reasoning, and Inference.

-   Angrist, J. D., & Pischke, J. S. 2008. Mostly harmless econometrics: An empiricist's companion. Princeton, NJ: Princeton University Press.

-   Greene, W. H. 2012. Econometric Analysis.

-   Hox, J. J., Moerbeek, M., & Schoot, R. V. D. 2017. Multilevel Analysis: Techniques and Applications. Quantitative Methodology Series.

-   Shadish, W. R., Cook, T. D., & Campbell, D. T. 2002. Experimental and Quasi-experimental Designs for Generalized Causal Inference. Cengage Learning.

-   Hastie, T., Tibshirani, R., & Friedman, J. 2016. The Elements of Statistical Learning: Data Mining, Inference, and Prediction (2nd Edition ed.). Springer.

-   Mershon, C., & Shvetsova, O. 2019. Formal Modeling in Social Science. University of Michigan Press.

#### *Electronic textbooks built with R Markdown (nice quick-access references):*

-   https://bookdown.org/ejvanholm/Textbook/

-   https://book.declaredesign.org/declaration-diagnosis-redesign/specifying-model.html

-   https://www.econometrics-with-r.org/

### VI. SCHOOL POLICIES

All courses offered at Bentley University reflect our institution's commitment to a set of core values and practices.  The links below will take you to full explanations of our policies and procedures related to accommodations and equitable learning environments. As a student, you are expected to review and be familiar with each of these policies:

-   [Bentley's honor code and academic integrity system](https://catalog.bentley.edu/graduate/academic-policies-procedures/academic-integrity/)

-   [Equity and bias reporting forms and procedures](https://www.bentley.edu/equity-reporting)

-   [Student Disability Accommodations](https://www.bentley.edu/offices/disability-services)

-   [Religious observances](https://catalog.bentley.edu/undergraduate/academic-policies-procedures/#Religious_Observances_Policy)

-   [Bentley's core values](https://www.bentley.edu/about/mission-and-values)

\blandscape

### VII. COURSE SCHEDULE

+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+
| **Week**                            | **Date** | **Topics**                     | **Key question** | **Tools**                  | **Deliverables**                     |
+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+
| **The Research Process**            |          |                                |                  |                            |                                      |
+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+
| 1                                   | 23-Jan   | Research I: Principles         | To what end?     |                            |                                      |
+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+
| 2                                   | 30-Jan   | Research II: Positions         | In what way?     |                            |                                      |
+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+
| 3                                   | 9-Feb    | Research III: Practices        | With what tools? |                            | Compare / contrast: 1-4\             |
|                                     |          |                                |                  |                            |                                      |
|                                     |          | \                              |                  |                            | **Research questions**               |
|                                     |          | *Workshop*                     |                  |                            |                                      |
+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+
| **The Elements of Research Design** |          |                                |                  |                            |                                      |
+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+
| 4                                   | 13-Feb   | Elements I:\                   | Why?             | Nomological networks       | Compare / contrast: 5-8              |
|                                     |          | Theory and phenomena           |                  |                            |                                      |
|                                     |          |                                |                  |                            | **Concept check 1\                   |
|                                     |          |                                |                  |                            | (due next class)**                   |
+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+
| 5                                   | 27-Feb   | Elements II:\                  | Testable?        | Formal models, DAGs        | Compare / contrast: 9-12             |
|                                     |          | Models and hypotheses          |                  |                            |                                      |
+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+
| 6                                   | 5-Mar    | Elements III:\                 | What?            | Validity assessments       | Compare / contrast: 13-16            |
|                                     |          | Constructs and variables       |                  |                            |                                      |
+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+
| 7                                   | 22-Mar   | Elements IV: Data and measures | Observable?      | Descriptive statistics     | Compare / contrast: 17-20\           |
|                                     |          |                                |                  |                            |                                      |
|                                     |          | *Workshop*                     |                  |                            | **Draft model**                      |
+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+
| **Core models and techniques**      |          |                                |                  |                            |                                      |
+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+
| 8                                   | 26-Mar   | Techniques I: Regression       | Valid?           | OLS, Statistical inference | Replication: 1,3,5\                  |
|                                     |          |                                |                  |                            |                                      |
|                                     |          |                                |                  |                            | **Concept check 2 (due next class)** |
+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+
| 9                                   | 2-Apr    | Techniques II: Moderation      | When?            | HLM, Interaction plots     | Replication: 2,4,6                   |
+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+
| 10                                  | 9-Apr    | Techniques III: Mediation      | How?             | SEM, Indirect effects      | Replication: 7,9,11                  |
+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+
| 11                                  | 16-Apr   | Techniques IV: Endogeneity     | Alternatives?    | 2SLS, Instruments          | Replication: 8,10,12                 |
+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+
| **Theory-empiric fit**              |          |                                |                  |                            |                                      |
+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+
| 12                                  | 26-Apr   | Design I: (Quasi)-experimental | Causal?          | D-i-D                      | Replication: 13,15,17,19             |
|                                     |          |                                |                  |                            |                                      |
|                                     |          | Design II: Longitudinal data   | Dynamic?         | Panel data estimators      | Replication: 14,16,18,20             |
|                                     |          |                                |                  |                            |                                      |
|                                     |          | *Workshop*                     |                  |                            | **Draft paper deliverable**          |
+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+
| 13                                  | 3-May    | *No class*                     |                  |                            | **Final deliverable due 5/3**        |
+-------------------------------------+----------+--------------------------------+------------------+----------------------------+--------------------------------------+

\elandscape

## APPENDIX A -- ASSIGNMENT DETAILS

### Class participation -- paper discussions

It is expected that students will have done the assigned readings in advance and be prepared to discuss them. As part of this preparation, I recommend that you put together an outline for each reading that captures (the below are illustrative examples):

-   key points of the paper
-   what insights you gained from reading the piece
-   questions to raise during the class
-   points of potential conflict between this work and others you have seen in the past
-   connections noted between this paper and others in the class and elsewhere
-   specific tools and techniques you can apply in the future (if applicable, will not always be the case)

The assigned readings for each week are provided in Appendix B.

I will also have a few questions written down for each paper for us to consider in case we need to get the ball rolling on the discussion; we may or may not discuss those questions depending on the flow of the class.

### Compare -- contrast presentations

You have been assigned a number (see the table at the end of this section for your assignment. Based on this number, you will be allocated to a group of students (see the "Deliverables" column in the Course Schedule above).

Collectively, your group will work together to perform a deeper reading of the two articles bulleted under the "Compare/Contrast" section of the week's reading. You will make a presentation regarding these two papers: their points of intersection and divergence, how they fit with the other readings assigned for the week, and their place within your broader understanding of management research to date.

It is expected that your group will lead a discussion of these concepts in class. During that period, I will take the role of an informed participant except in cases when I need to clarify points of potential confusion.

### Replication presentations

As discussed above, you have been assigned a number (see the table at the end of this section for your assignment). Based on this number, you will be allocated to a different group of students (please note that the group assignments differ from the compare / contrast presentations, so that we can mix up group composition).

Collectively, your group will work together to re-analyze the data for an in-progress or completed paper of mine. The objective here is for you to get hands-on experience with using the analytical tools that support these analyses and report your experience to the class. The paper will be provided to you as part of the packet of readings.

I can also provide your group with the underlying data to complete your analyses, on an as-needed basis. I am also happy to work with your group to walk through questions and concerns that you have in performing the assignment.

It is expected that your group will lead a discussion of this effort in class and to explain what went well, what didn't go as well, and what analyses and conclusions of the paper you were able to replicate and which you could not.

### Concept checks

There will be two "concept checks" during the course of the semester -- they will be administered online, outside of class. They serve two purposes: a) identifying areas where I have not communicated concepts adequately, and b) giving you an incentive to keep up with the readings. The typical format is 10-15 multiple choice questions that call upon you to apply the lessons of the classes that we have covered up until that point.

### Research proposals

#### Interim work - Research questions

During our first in-person meeting, we will have a workshop session about four hours long. For the first two hours or so, students will make a five-minute presentation about their research topic/idea for their dissertation. This can involve a few PowerPoint slides to help guide the discussion. It may be a broad topic or specific question; this will vary by student. The purpose of the presentation is to introduce this research to the class at the beginning of the seminar and to get you thinking about it. This will be graded by the presence or absence of your preparation for this session. The balance of the workshop will be group work to discuss and advance those research questions, where I will move from group to group to facilitate discussions.

#### Interim work - Draft model

During our second in-person meeting, we will have another workshop session about four hours long. For the first two hours or so, students will make a five-minute presentation about the draft model that they will examine for their dissertation work that builds upon their research topic/idea. Again, this can involve a few PowerPoint slides to help guide the discussion. This will be graded by the presence or absence of your preparation for this session. The balance of the workshop will be group work to discuss and advance those research questions, where I will move from group to group to facilitate discussions.

#### Interim work - Draft deliverable

This is your opportunity to submit a first draft of your paper to receive feedback from me and your colleagues. Our final workshop will be structured as two sets of working sessions where you will be working with two different classmates to review and advance elements your draft. I will be going from group to group in order to answer questions and get read-outs of progress from each group. My expectation is that you will have the "front end" of the paper (introduction, hypotheses) more progressed than the methods section given the order of the content we are covering in class. As for the content that should be coming together in this first draft, please see the discussion of the final deliverable below.

#### Final deliverable

Your final deliverable is a drafted introduction, model development, and methods section that supports the research model you seek to examine. The purpose of the assignment is twofold:

-   to make forward progress on your dissertation work that incorporates some of the skills you have acquired during the course
-   to apply and integrate the concepts and issues being studied in this course regarding quantitative research design and method. Ideally, this proposal, once converted to a complete paper, would be of publishable standard, either as a conference paper, or for subsequent submission to a peer-reviewed journal. In terms of the format, here is a suggested structure for you to follow:
    1.  Cover page (include a title, your name, and an abstract)
    2.  Introduction (2-4 pages)
    3.  Theory and Hypotheses (5-10 pages)
    4.  Methods (5-10 pages)\
        I would encourage you to draw upon the existing empirical papers that you have read in this class and previous classes as models for how to structure these various sections, in addition to the explicit guidance provided in the readings from the course. To provide a few examples:
        -   Lange and Pfarrer, (2017) \[Week: Research III: Practices\] provide some nice suggestions for how to structure introductions
        -   Suddaby (2010) \[Week Elements III: Constructs and variables\] shares guidance on how to make sure that your constructs are sufficiently articulated in your theory development
        -   Mathieu and Taylor (2006) \[Week Techniques III: Mediation\] develops a checklist of steps to perform in order to draw particular mediational inferences and rule out alternative configurations

Please feel free to reach out to me with questions as you work on this assignment. If a question comes to my attention that would be useful for the whole class to talk about, I will set aside time during the following session to discuss it.

### Assignment table for group composition

|            |                          |
|------------|--------------------------|
| **Number** | **Name**                 |
| 1          | Shardul Wartikar         |
| 2          | Ed Wogan                 |
| 3          | Lakia Rutherford-Sargent |
| 4          | Conor Long               |
| 5          | Esteban Lopez Meneses    |
| 6          | Kay Anifowose            |
| 7          | Nicholas Svizzero        |
| 8          | Ike Okonkwo              |
| 9          | Reuben Brefo Marfo       |
| 10         | Dan Berlin               |
| 11         | Esel Shemmeri            |
| 12         | Yulu Du                  |
| 13         | Kali Maltese             |
| 14         | Tammy Rose               |
| 15         | Scott Keaney             |
| 16         | Tarry Gutzmore           |
| 17         | Bryan Drake              |
| 18         | Cynthia Fernandes        |
| 19         | Ralph Faber              |
| 20         | Booma Yandava            |

## APPENDIX B -- READINGS BY TOPIC

A Dropbox link is available on Brightspace, which provides access to all of these readings by class, including book chapters (where applicable).

### Research I: Principles

1.  Popper, K. R. (2002). The Logic of Scientific Discovery. Routledge. \[Ch .1\]

2.  Mantere, S., & Ketokivi, M. 2013. Reasoning in Organization Science. Academy of Management Review, 38(1), 70-89.

3.  Nosek, B. A. & Errington, T. M. 2020. What is replication? PLOS Biology: 1-8.

4.  Rynes, S. L., & Bartunek, J. M. (2017). Evidence-Based Management: Foundations, Development, Controversies and Future. Annual Review of Organizational Psychology and Organizational Behavior, 4(1), 235-261. <https://doi.org/10.1146/annurev-orgpsych-032516-113306>

### Research II: Positions

1.  Huff, A. S. (1999). Writing for Scholarly Publication. SAGE. \[Chs. 1, 3\]

2.  McGrath, Joseph E. (1981) Dilemmatics: The Study of Research Choices and Dilemmas, American Behavioral Scientist, 25, 2, 179-210

3.  Simsek, Z., Heavey, C., Fox, B. C., & Yu, T. 2022. Compelling Questions in Research: Seeing What Everybody Has Seen and Thinking What Nobody Has Thought. Journal of Management, 48(6), 1347-1365.

4.  Tushman, M., & O’Reilly, C. (2007). Research and Relevance: Implications of Pasteur’s Quadrant for Doctoral Programs and Faculty Development. The Academy of Management Journal, 50, No. 4, 769-774. <https://doi.org/10.2307/20159888>

### Research III: Practices

1.  Lange, D., & Pfarrer, M. D. (2017). Editors' Comments: Sense and Structure---The Core Building Blocks of an AMR Article. Academy of Management Review, 42(3), 407-416. https://doi.org/10.5465/amr.2016.0225

2.  Tobi, H., & Kampen, J. K. 2018. Research design: the methodology for interdisciplinary research framework. Qual Quant, 52(3), 1209-1225.

3.  Aguinis, H. & Vandenberg, R. J. (2014). An ounce of prevention is worth a pound of cure: improving research quality before data collection. Annual Review of Organizational Psychology and Organizational Behavior, 1: 569-595.

4.  Compare / Contrast

-   Corley, K. G., & Gioia, D. A. (2011). Building Theory about Theory Building: What Constitutes a Theoretical Contribution. Academy of Management Review, 36(1), 12-32. https://doi.org/10.5465/amr.2009.0486

-   David A. Whetten, 1989. What constitutes a theoretical contribution? Academy of Management Review, 14: 490-495

### Elements I: Theory and phenomena

1.  Bacharach, S. B. (1989). Organizational Theories: Some Criteria for Evaluation. The Academy of Management Review, 14(4), 496-515. https://doi.org/10.2307/258555

2.  Makadok, R., Burton, R., & Barney, J. (2018). A practical guide for making theory contributions in strategic management. Strategic Management Journal, 39(6), 1530-1545. <https://doi.org/10.1002/smj.2789>

3.  Johns, G. 2006. The Essential Impact of Context on Organizational Behavior. The Academy of Management Review, 31, No. 2, 386-408.

4.  Compare / contrast

-   Sutton, R. I., & Staw, B. M. (1995). What Theory is Not. Administrative Science Quarterly, 40(3), 371. <https://doi.org/10.2307/2393788>

-   Hambrick, D. C. 2007. The field of management's devotion to theory: Too much of a good thing? Academy of Management Journal, 50, 1346-1352.

### Elements II: Models and hypotheses

1.  Harris, J. D., Johnson, S. G., & Souder, D. 2013. Model-Theoretic Knowledge Accumulation: The Case of Agency Theory and Incentive Alignment. Academy of Management Review, 38(3), 442-454.

2.  Chamberlin, T. C. (1965). The Method of Multiple Working Hypotheses. Science, 148(3671), 754-759. https://doi.org/10.1126/science.148.3671.754

3.  Pearl, J. 2010. 3. The Foundations of Causal Inference. Sociological Methodology, 40(1), 75-149.

4.  Compare / contrast

-   Adner, R., Pólos, L., Ryall, M., & Sorenson, O. 2009. The Case for Formal Theory. Academy of Management Review, 34(2), 201-208.

-   Miller, K. D. & Tsang, E. W. K. 2011. Testing management theories: Critical realist philosophy and research methods. Strategic Management Journal, 32(2): 139-158.

### Elements III: Constructs and variables

1.  Suddaby, R. (2010). Editor's Comments: Construct Clarity in Theories of Management and Organization. Academy of Management Review, 35(3), 346-357. https://doi.org/10.5465/amr.35.3.zok346

2.  Van Maanen, J., Sorensen, J. B., & Mitchell, T. R. 2007. The interplay between theory and method. Academy of Management Review 32(4): 1145-1154.

3.  Bagozzi, R. P., Yi, Y., & Phillips, L. W. (1991). Assessing Construct Validity in Organizational Research. Administrative Science Quarterly, 36, No. 3, 421-458. https://doi.org/10.2307/2393203

4.  Compare / contrast

-   Schaffer, J. A., DeGeest, D., & Li, A. 2016. Tackling the problem of construct proliferation: A guide to assessing discriminant validity of conceptually related constructs. Organizational Research Methods, 19: 80- 110.

-   Law, K. S., Wong, C.-S., & Mobley, W. H. (1998). Toward a Taxonomy of Multidimensional Constructs. The Academy of Management Review, 23(4), 741. https://doi.org/10.2307/259060

### Elements IV: Data and measures

1.  Stevens, S. S. 1946. On the Theory of Scales of Measurement. Science, New Series, 103, No. 2684, 677-680.

2.  Bedian, A. G. 2014. "More Than Meets the Eye": A Guide to Interpreting the Descriptive Statistics and Correlation Matrices Reported in Management Research. Academy of Management Learning & Education, 13, No. 1, 121-135.

3.  Heggestad, E. D., Scheaf, D. J., Banks, G. C., Monroe Hausfeld, M., Tonidandel, S., & Williams, E. B. (2019). Scale Adaptation in Organizational Science Research: A Review and Best-Practice Recommendations. Journal of Management, 45(6), 2596-2627.

4.  Compare / contrast

-   Combs, J. G. 2010. Big samples and small effects: Let's not trade relevance and rigor for power. Academy of Management Journal, 53(1): 9-13.

-   Simsek, Z., Vaara, E., Parachuri, S., Nadkarni, S., & Shaw, J. D. 2019. New ways of seeing big data. Academy of Management Journal, 62: 971-978.

### Techniques I: Regression

1.  Kennedy, P. 2008. A Guide to Econometrics (6th Edition ed.). Malden, MA: Blackwell. \[Chs. 3 and 4\]

2.  Carlson, K. D., & Wu, J. 2012. The illusion of statistical control: Control variable practice in management.

Applications:

3.  Replication: Simsek, Z., Fox, B., & Heavey, C. 2021. Systematicity in Organizational Research Literature Reviews: A Framework and Assessment. Organizational Research Methods, 109442812110086.

4.  Katila, R., & Ahuja, G. 2002. Something Old, Something New: A Longitudinal Study of Search Behavior and New Product Introduction. Academy of Management Journal, 45(6), 1183-1194.

### Techniques II: Moderation

1.  Dawson, J. F. 2014. Moderation in Management Research: What, Why, When, and How. Journal of Business and Psychology, 29(1), 1-19.

2.  Hitt, M. A., Beamish, P. W., Jackson, S. E., & Mathieu, J. E. 2007. Building Theoretical and Empirical Bridges Across Levels: Multilevel Research in Management. Academy of Management Journal, 50(6), 1385-1399.

Applications:

3.  Replication: Heavey, C., Simsek, Z., & Fox, B. C. 2015. Managerial Social Networks and Ambidexterity of SMEs: The Moderating Role of a Proactive Commitment to Innovation. Human Resource Management, 54(S1).

4.  Wolfson, M. A., & Mathieu, J. E. 2018. Sprinting to the finish: Toward a theory of Human Capital Resource Complementarity. J Appl Psychol, 103(11), 1165-1180.

### Techniques III: Mediation

1.  Mathieu, J. E., & Taylor, S. R. 2006. Clarifying conditions and decision points for mediational type inferences in Organizational Behavior. Journal of Organizational Behavior, 27(8), 1031-1056.

2.  Williams, L. J., Vandenberg, R. J., & Edwards, J. R. 2009. 12 Structural Equation Modeling in Management Research: A Guide for Improved Analysis. Academy of Management Annals, 3(1), 543-604.

Applications:

3.  Ling, Y., Simsek, Z., Lubatkin, M. H., & Veiga, J. F. 2008. Transformational Leadership's Role in Promoting Corporate Entrepreneurship: Examining the CEO-TMT Interface. Academy of Management Journal, 51(3), 557-576.

4.  Replication: Fox, B. C., Simsek, Z., & Heavey, C. 2022. Top Management Team Experiential Variety, Competitive Repertoires, and Firm Performance: Examining the Law of Requisite Variety in the 3D Printing Industry (1986--2017). Academy of Management Journal, 65(2), 545-576.

### Techniques IV: Endogeneity

1.  Cuervo-Cazurra, A., Andersson, U., Brannen, M. Y., Nielsen, B. B., & Reuber, R. A. 2016. From the Editors: Can I trust your findings? Ruling out alternative explanations in international business research. Journal of International Business Studies, 47(8), 881-897.

2.  Hamilton, B. H., & Nickerson, J. A. 2003. Correcting for endogeneity in strategic management research. Strategic Organization, 1(1): 51-78.

Applications:

3.  Angrist, J. D., & Krueger, A. B. 1991. Does Compulsory School Attendance Affect Schooling and Earnings. The Quarterly Journal of Economics, 106(4), 979-1014.
4.  Replication: Fox, B. C., Simsek, Z., & Heavey, C. 2023. Venture team membership dynamics and new venture innovation. Strategic Entrepreneurship Journal.

### Design I: (Quasi-)experimental data

1.  Grant, A. M., & Wall, T. D. 2009. The Neglected Science and Art of Quasi-Experimentation. Organizational Research Methods, 12(4), 653-686.

2.  Shadish, W. R., & Cook, T. D. 2009. The renaissance of field experimentation in evaluating interventions. Annu Rev Psychol, 60, 607-629.

Applications:

3.  Shu, L. L., Mazar, N., Gino, F., Ariely, D., & Bazerman, M. H. (2012). Signing at the beginning makes ethics salient and decreases dishonest self-reports in comparison to signing at the end. Proceedings of the National Academy of Sciences, 109(38), 15197--15200. doi:10.1073/pnas.1209746109 (see also https://datacolada.org/109)

4.  Replication: Penrosian capacity as a constraint on entrepreneurial growth: An exploratory study employing the dot-com bubble (working paper)

### Design II: Longitudinal data

1.  Ployhart, R.E. and R.J. Vandenberg. 2010. Longitudinal Research: The Theory, Design and Analysis of Change. Journal of Management, 36(1): 94-120.

2.  Mitchell, T. R. & James, L. R. 2001. Building better theory: Time and the specification of when things happen. Academy of Management Review, 26: 530-548. Applications:

Applications:

3.  Certo, S. T., Withers, M. C., & Semadeni, M. 2017. A tale of two effects: Using longitudinal data to compare within- and between-firm effects. Strategic Management Journal, 38(7), 1536-1556.
4.  Replication: Firm Repertoires and Performance: The Influence of Complementarity and Competition (working paper)
